### PR TITLE
Feature/sinf 211 bat alb certs

### PR DESCRIPTION
**Pull request by adrianmilne**
No rush for this - but thought I'd push the PR now.

Changes have been applied to SBX1 - they don't work, but I'm just wondering if that is just DNS propagation delays.

I won't merge anything until I've seen it working...

### CODE REVIEW

**Comment by tommyb82** [comment]
Looking good - just applied to SBX2 no problems.  Do you think we can remove the port 80 LB listeners from the client and spree backend ECS modules now? They would seem redundant... 🤔

**Comment by adrianmilne** [comment]
> Looking good - just applied to SBX2 no problems. Do you think we can remove the port 80 LB listeners from the client and spree backend ECS modules now? They would seem redundant... 🤔

Yep - good point - I'll take a look at that 👍

**Comment by tommyb82** [comment]
Another question - is it worth taking this opportunity to rip out the 2 additional load balancers created as part of this infra and instead hook into the main Scale external one created in the shared-infra (for the R53 alias, listeners and target groups I mean) - this is supported I think: https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/#ALB

**Review by tommyb82 — APPROVED** [review]
Great stuff 👍

**Pull request merged**
