### PR TITLE
SINF-235 - added SBX8

### PR DESCRIPTION
**Pull request by adrianmilne**
Had to give memcached a specific engine version as I think the default one has now moved to 1.6 (which is incompatible with the specified 1.5 parameter group.

Applied on SBX8

### CODE REVIEW

**Comment by tommyb82** [comment]
> Had to give memcached a specific engine version as I think the default one has now moved to 1.6 (which is incompatible with the specified 1.5 parameter group.
> 
> Applied on SBX8

Well, hopefully it will be out of the equation soon.. 😎

**Review by tommyb82 — APPROVED** [review]
Great, good job keeping the post-deployment task list up to date (or attempting to!) 👍

**Comment by adrianmilne** [comment]
> Great, good job keeping the post-deployment task list up to date (or attempting to!) 👍

Cheers - I was a bit premature putting this PR in - still got some REAMDE changes to add based on the work Tony is doing - I'll get them in and merge once we get the green light it all looks ok

**Review by tommyb82 — APPROVED** [review]
Excellent 👍

**Pull request merged**
